apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ha-{{ .Values.tenant.name }}
  
data:
  haproxy.cfg: |
    global
    	daemon
    	maxconn 256
    
    defaults
    	mode tcp
    	timeout connect 5000ms
    	timeout client 50000ms
    	timeout server 50000ms
    
    
    frontend http
    	bind :8080
    	default_backend stats
    
    
    backend stats
    	mode http
    	stats enable
    
    	stats enable
    	stats uri /
    	stats refresh 1s
    	stats show-legends
    	stats admin if TRUE
    
    resolvers k8s
      parse-resolv-conf
      hold other           10s
      hold refused         10s
      hold nx              10s
      hold timeout         10s
      hold valid           10s
      hold obsolete        10s
    
    frontend redis-read
    	bind *:6380
        default_backend redis-online
    
    
    frontend redis-write
        bind *:6379
    	default_backend redis-primary
    
    
    backend redis-primary
    	mode tcp
    	balance first
    	option tcp-check
    	tcp-check send info\ replication\r\n
    	tcp-check expect string role:master
      server-template redis 3 _tcp-redis._tcp.redis-{{ .Values.tenant.name }}-headless.redis.svc.cluster.local:6379 check inter 1s resolvers k8s init-addr none
    
    
    backend redis-online
    	mode tcp
    	balance roundrobin
    	option tcp-check
    	tcp-check send PING\r\n
    	tcp-check expect string +PONG
      server-template redis 3 _tcp-redis._tcp.redis-{{ .Values.tenant.name }}-headless.redis.svc.cluster.local:6379 check inter 1s resolvers k8s init-addr none
