apiVersion: v1
kind: Service
metadata:
  name: redis-ha-{{ .Values.tenant.name }}
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.metallb.addressPool | default "" | quote }}
  labels:
    app: redis-ha-{{ .Values.tenant.name }}
spec:
  type: LoadBalancer
  ports:
    - name: dashboard
      port: 8080
      targetPort: 8080
    - name: redis-write
      port: 6379
      targetPort: 6379
    - name: redis-read
      port: 6380
      targetPort: 6380
  selector:
    app: redis-ha-{{ .Values.tenant.name }}